#### List

In [2]:
a = []
b = [1,2,3]
c = ['a', 'b', 'c']
d = [1, 'q', 2]
print(type(a), type(b), type(c), type(d))

<class 'list'> <class 'list'> <class 'list'> <class 'list'>


In [3]:
print(a + b)

[1, 2, 3]


In [5]:
a = [1, 2, 3]
b = [3, 4, 5]
print(a + b)

[1, 2, 3, 3, 4, 5]


In [27]:
a = [1, 2, 3]
b = ['a', 'b', 'c']
print(a + b)

[1, 2, 3, 'a', 'b', 'c']


In [28]:
a.append(3)
print(a)

[1, 2, 3, 3]


In [29]:
a.append(b)
print(a)

[1, 2, 3, 3, ['a', 'b', 'c']]


In [37]:
a = [1, 2, 3]
a * 3

[1, 2, 3, 1, 2, 3, 1, 2, 3]

#### Numpy array 

In [38]:
import numpy as np

In [39]:
np.array([1, 2, 3])

array([1, 2, 3])

In [40]:
a = np.array([1, 2, 3])
b = np.array([3, 4, 5])
print(a, b)

[1 2 3] [3 4 5]


In [41]:
print(a + b)

[4 6 8]


In [42]:
a.append(4)

AttributeError: 'numpy.ndarray' object has no attribute 'append'

In [43]:
np.append(a, 4)

array([1, 2, 3, 4])

In [44]:
np.append(a, b)

array([1, 2, 3, 3, 4, 5])

In [46]:
a * 3

array([3, 6, 9])

In [47]:
array_a = np.array([[1, 2, 3], [2, 3, 4]])

In [48]:
array_a.shape

(2, 3)

In [49]:
array_b = np.array([1, 2, 3, 4, 5, 6, 7, 8])
print(array_b)

[1 2 3 4 5 6 7 8]


In [50]:
array_b.reshape(2, 4)

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [51]:
array_b.reshape(1,8)

array([[1, 2, 3, 4, 5, 6, 7, 8]])

In [54]:
array_b.reshape(8,)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [55]:
array_b.reshape(,8)

SyntaxError: invalid syntax (<ipython-input-55-9e622b51f858>, line 1)

In [56]:
array_a.reshape(6, )

array([1, 2, 3, 2, 3, 4])

In [58]:
print(array_a, array_b)

[[1 2 3]
 [2 3 4]] [1 2 3 4 5 6 7 8]


In [59]:
array_a + [1, 2]

ValueError: operands could not be broadcast together with shapes (2,3) (2,) 

In [60]:
array_a + [1, 2, 3]

array([[2, 4, 6],
       [3, 5, 7]])

In [61]:
array_a[1] + [1, 2, 3]

array([3, 5, 7])

In [62]:
array_a[0] = array_a[1] + [1, 2, 3]

In [63]:
array_a

array([[3, 5, 7],
       [2, 3, 4]])